version: '3'
services:
  app:
    image: go-bipul-in-app
    container_name: go-bipul-in-app
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/go-bipul-in-app
      - /usr/src/go-bipul-in-app/node_modules # Prevent overwriting node_modules
    command: >
      sh -c "yarn install && yarn dev"