version: '3'
services:
  app:
    container_name: go_bipul_in
    build: .
    ports:
      - "8081:8081"
    volumes:
      - .:/usr/src/go-bipul-app:cached
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100